name: jupyterlab_cis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex>=0.1
  - _r-mutex>=1.0.1
  - attrs>=19.3.0
  - backcall>=0.1.0
  - binutils_impl_linux-64>=2.31.1
  - binutils_linux-64>=2.31.1
  - bleach>=3.1.5
  - brotlipy>=0.7.0
  - bwidget>=1.9.14
  - bzip2>=1.0.8
  - ca-certificates>=2020.4.5.1
  - cairo>=1.16.0
  - certifi>=2020.4.5.1
  - cffi>=1.14.0
  - chardet>=3.0.4
  - cmake>=3.14.0
  - cryptography>=2.9.2
  - curl>=7.69.1
  - cycler>=0.10.0
  - czmq>=4.2.0
  - decorator>=4.4.2
  - defusedxml>=0.6.0
  - entrypoints>=0.3
  - expat>=2.2.9
  - fastcache>=1.1.0
  - flaky>=3.6.1
  - fontconfig>=2.13.1
  - freetype>=2.10.2
  - fribidi>=1.0.9
  - gcc_impl_linux-64>=7.3.0
  - gcc_linux-64>=7.3.0
  - gettext>=0.19.8.1
  - gfortran_impl_linux-64>=7.3.0
  - gfortran_linux-64>=7.3.0
  - git>=2.27.0
  - gitdb>=4.0.5
  - gitpython>=3.1.3
  - glib>=2.63.1
  - gmp>=6.2.0
  - gmpy2>=2.1.0b1
  - graphite2>=1.3.13
  - gsl>=2.6
  - gxx_impl_linux-64>=7.3.0
  - gxx_linux-64>=7.3.0
  - harfbuzz>=2.4.0
  - icu>=64.2
  - idna>=2.9
  - importlib-metadata>=1.6.0
  - ipykernel>=5.3.0
  - ipython>=7.15.0
  - ipython_genutils>=0.2.0
  - ipywidgets>=7.5.1
  - jedi>=0.17.0
  - jinja2>=2.11.2
  - jpeg>=9d
  - json5>=0.9.0
  - jsonschema>=3.2.0
  - jupyter_client>=6.1.3
  - jupyter_core>=4.6.3
  - jupyterlab>=2.1.3
  - jupyterlab_server>=1.1.5
  - kiwisolver>=1.2.0
  - krb5>=1.17.1
  - ld_impl_linux-64>=2.33.1
  - libblas>=3.8.0
  - libcblas>=3.8.0
  - libcurl>=7.69.1
  - libedit>=3.1.20181209
  - libffi>=3.3
  - libgcc>=7.2.0
  - libgcc-ng>=9.1.0
  - libgfortran-ng>=7.5.0
  - libiconv>=1.15
  - liblapack>=3.8.0
  - libopenblas>=0.3.7
  - libpng>=1.6.37
  - libsodium>=1.0.17
  - libssh2>=1.9.0
  - libstdcxx-ng>=9.1.0
  - libtiff>=4.1.0
  - libuuid>=2.32.1
  - libuv>=1.38.0
  - libwebp-base>=1.1.0
  - libxcb>=1.13
  - libxml2>=2.9.10
  - lz4-c>=1.9.2
  - make>=4.3
  - markupsafe>=1.1.1
  - matplotlib-base>=3.2.1
  - mistune>=0.8.4
  - mpc>=1.1.0
  - mpfr>=4.0.2
  - mpmath>=1.1.0
  - nbconvert>=5.6.1
  - nbformat>=5.0.6
  - nbgitpuller>=0.8.0
  - ncurses>=6.2
  - networkx>=2.4
  - nodejs>=6.13.1
  - notebook>=6.0.3
  - numpy>=1.18.4
  - openssl>=1.1.1g
  - packaging>=20.4
  - pandas>=1.0.4
  - pandoc>=2.9.2.1
  - pandocfilters>=1.4.2
  - pango>=1.42.4
  - parso>=0.7.0
  - pcre>=8.44
  - pcre2>=10.34
  - perl>=5.26.2
  - pexpect>=4.8.0
  - pickleshare>=0.7.5
  - pip>=20.0.2
  - pixman>=0.38.0
  - plotly>=4.8.1
  - prometheus_client>=0.8.0
  - prompt-toolkit>=3.0.5
  - psutil>=5.7.0
  - pthread-stubs>=0.4
  - ptyprocess>=0.6.0
  - pycparser>=2.20
  - pygments>=2.6.1
  - pyopenssl>=19.1.0
  - pyparsing>=2.4.7
  - pyperf>=2.0.0
  - pyrsistent>=0.16.0
  - pysocks>=1.7.1
  - pystache>=0.5.4
  - python>=3.7.7
  - python-dateutil>=2.8.1
  - python-rapidjson>=0.9.1
  - python_abi>=3.7
  - pytz>=2020.1
  - pyyaml>=5.3.1
  - pyzmq>=19.0.1
  - r-base>=4.0.0
  - r-bit>=1.1_15.2
  - r-bit64
  - r-jsonlite>=1.6.1
  - r-lattice>=0.20_41
  - r-matrix>=1.2_18
  - r-r6>=2.4.1
  - r-rappdirs
  - r-rcpp>=1.0.4.6
  - r-reticulate>=1.16
  - r-units>=0.6_6
  - r-zeallot>=0.1.0
  - readline>=8.0
  - requests>=2.23.0
  - retrying>=1.3.3
  - rhash>=1.3.8
  - scipy>=1.4.1
  - sed>=4.7
  - send2trash>=1.5.0
  - setuptools>=47.1.1
  - six>=1.15.0
  - smmap>=3.0.4
  - sqlite>=3.31.1
  - sympy>=1.6
  - sysv_ipc>=1.0.1
  - terminado>=0.8.3
  - testpath>=0.4.4
  - tk>=8.6.10
  - tktable>=2.10
  - tornado>=6.0.4
  - traitlets>=4.3.3
  - typescript>=3.6.4
  - udunits2>=2.2.27.6
  - unyt>=2.7.1
  - urllib3>=1.25.9
  - wcwidth>=0.2.3
  - webencodings>=0.5.1
  - wheel>=0.34.2
  - widgetsnbextension>=3.5.1
  - xorg-kbproto>=1.0.7
  - xorg-libice>=1.0.10
  - xorg-libsm>=1.2.3
  - xorg-libx11>=1.6.9
  - xorg-libxau>=1.0.9
  - xorg-libxdmcp>=1.1.3
  - xorg-libxext>=1.3.4
  - xorg-libxrender>=0.9.10
  - xorg-renderproto>=0.11.1
  - xorg-xextproto>=7.3.0
  - xorg-xproto>=7.0.31
  - xz>=5.2.5
  - yaml>=0.2.5
  - yarn>=1.22.4
  - yggdrasil>=1.1.1
  - zeromq>=4.3.2
  - zipp>=3.1.0
  - zlib>=1.2.11
  - zstd>=1.4.4
  - pip:
    - matlab-kernel>=0.16.9
    - metakernel>=0.24.4
    - wurlitzer>=2.0.0
